name: Deploy Production

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. เช็กโค้ด
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. ล็อกอิน (พิมพ์ใหม่ให้ชัวร์)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. สร้าง Backend
      - name: Build Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest

      # 4. สร้าง Frontend
      - name: Build Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend:latest

      # 5. สั่ง Server (Deploy)
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OLS_HOST }}
          username: ${{ secrets.OLS_USERNAME }}
          key: ${{ secrets.OLS_SSH_KEY }}
          script: |
            cd /root/myapp
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
